# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'education_trata_swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for education_trata_swift
  pod 'Charts'

end
